#remote_theme: "mmistakes/so-simple-theme@3.2.0"

#plugins:
#- jekyll-remote-theme

#logo: /images/logo.jpg

theme: minima

title: Companion 2

baseurl: "./seminar/companion2"

header_pages: seminar/companion2.md

categories: markdown

