#remote_theme: "mmistakes/so-simple-theme@3.2.0"

#plugins:
#- jekyll-remote-theme

#logo: /images/logo.jpg
title: Compainion

baseurl: "/seminar/companion2"

header_pages: seminar/companion2.

categories: markdown